apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv1-rwx
  namespace: parallel
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem

